### PR TITLE
Fix FH lifecycle

### PR DESCRIPTION
**Pull request by danielpassos**
See: [FHTEMPLATE-19](https://issues.jboss.org/browse/FHTEMPLATE-19)

### CODE REVIEW

**Comment by secondsun** [comment]
+1

**Comment by danielpassos** [comment]
@wei-lee Could you give it a spin?

**Comment by secondsun** [comment]
@danielpassos Can you rebase on master?

**Comment by danielpassos** [comment]
@secondsun  Done!

**Pull request closed without merging**
